Repository SOPT-all/35-APPJAM-SERVER-memento, pull requests merged in 2025-01, with the labels that each got.

#4 setting: Global package 세팅
  build.gradle.kts
  src/main/java/com/official/memento/global/stereotype/Adapter.java
  src/main/kotlin/com/official/memento/alarm/application/command/AlarmSendCommand.kt
  src/main/kotlin/com/official/memento/alarm/controller/AlarmApi.kt
  src/main/kotlin/com/official/memento/alarm/controller/AlarmApiDocs.kt
  src/main/kotlin/com/official/memento/alarm/controller/dto/AlarmRequest.kt
  src/main/kotlin/com/official/memento/alarm/domain/port/AlarmOutputPort.kt
  src/main/kotlin/com/official/memento/alarm/infrastructure/client/AlarmSendClientAdapter.kt
  src/main/kotlin/com/official/memento/alarm/presentation/dto/AlarmRequest.kt
  src/main/kotlin/com/official/memento/alarm/service/command/AlarmSendCommand.kt
  src/main/kotlin/com/official/memento/alarm/service/command/AlarmService.kt
  src/test/kotlin/com/official/memento/MementoApplicationTests.kt
Labels: setting

#9 feat: Token 검증을 위한 AuthorizationArgumentResolver 추가
  src/main/java/com/official/memento/global/annotation/Authorization.java
  src/main/java/com/official/memento/global/annotation/AuthorizationUser.java
  src/main/java/com/official/memento/global/resolver/AuthArgumentResolver.java
Labels: enhancement

#16 feat: Tag 생성 API 구현
  .github/auto_assign.yml
  src/main/java/com/official/memento/global/exception/EntityNotFoundException.java
  src/main/java/com/official/memento/global/exception/ErrorCode.java
  src/main/java/com/official/memento/tag/controller/TagApiController.java
  src/main/java/com/official/memento/tag/controller/TagApiDocs.java
  src/main/java/com/official/memento/tag/controller/dto/TagCreateRequest.java
  src/main/java/com/official/memento/tag/controller/dto/TagCreateResponse.java
  src/main/java/com/official/memento/tag/domain/Tag.java
  src/main/java/com/official/memento/tag/domain/TagRepository.java
  src/main/java/com/official/memento/tag/infrastructure/TagRepositoryAdapter.java
  src/main/java/com/official/memento/tag/infrastructure/persistence/TagEntity.java
  src/main/java/com/official/memento/tag/service/TagCreateUseCase.java
  src/main/java/com/official/memento/tag/service/TagService.java
  src/main/java/com/official/memento/tag/service/command/TagCreateCommand.java
Labels: enhancement

#18 태그 생성 API 리팩토링
  CODEOWNERS
  src/main/java/com/official/memento/tag/controller/TagApiController.java
  src/main/java/com/official/memento/tag/controller/TagApiDocs.java
  src/main/java/com/official/memento/tag/controller/dto/TagCreateRequest.java
  src/main/java/com/official/memento/tag/controller/dto/TagCreateResponse.java
  src/main/java/com/official/memento/tag/domain/enums/TagColor.java
  src/main/java/com/official/memento/tag/service/TagService.java
  src/main/java/com/official/memento/tag/service/command/TagCreateCommand.java
Labels: refactor

#33 Feature/#27 create todo
  src/main/java/com/official/memento/todo/domain/ToDo.java
  src/main/java/com/official/memento/todo/domain/ToDoRepository.java
  src/main/java/com/official/memento/todo/domain/ToDoTag.java
  src/main/java/com/official/memento/todo/domain/ToDoTagRepository.java
Labels: DO NOT MERGE‼️

#31 feat: 아이젠아워 매트릭스 관련 util 개발
  src/main/java/com/official/memento/global/util/EisenhowerDistanceUtil.java
  src/main/java/com/official/memento/todo/domain/enums/EisenhowerMatrixQuadrant.java
Labels: enhancement

#28 스케줄 도메인 구현
  src/main/java/com/official/memento/global/dto/SuccessResponse.java
  src/main/java/com/official/memento/global/entity/enums/RepeatOption.java
  src/main/java/com/official/memento/global/exception/EntityNotFoundException.java
  src/main/java/com/official/memento/global/exception/NullPointException.java
  src/main/java/com/official/memento/schedule/conntroller/ScheduleApiController.java
  src/main/java/com/official/memento/schedule/conntroller/ScheduleApiControllerDocs.java
  src/main/java/com/official/memento/schedule/conntroller/dto/request/RepeatScheduleCreateRequest.java
  src/main/java/com/official/memento/schedule/conntroller/dto/request/ScheduleCreateRequest.java
  src/main/java/com/official/memento/schedule/conntroller/dto/response/ScheduleCreateResponse.java
  src/main/java/com/official/memento/schedule/domain/Schedule.java
  src/main/java/com/official/memento/schedule/domain/ScheduleRepository.java
  src/main/java/com/official/memento/schedule/domain/ScheduleTag.java
  src/main/java/com/official/memento/schedule/domain/ScheduleTagRepository.java
  src/main/java/com/official/memento/schedule/domain/enums/RepeatOption.java
  src/main/java/com/official/memento/schedule/domain/enums/ScheduleType.java
  src/main/java/com/official/memento/schedule/infrastructure/ScheduleRepositoryAdapter.java
  src/main/java/com/official/memento/schedule/infrastructure/ScheduleTagRepositoryAdapter.java
  src/main/java/com/official/memento/schedule/infrastructure/persistence/ScheduleEntity.java
  src/main/java/com/official/memento/schedule/infrastructure/persistence/ScheduleTagEntity.java
  src/main/java/com/official/memento/schedule/infrastructure/persistence/ScheduleTagEntityJpaRepository.java
  src/main/java/com/official/memento/schedule/service/RepeatScheduleCreateUseCase.java
  src/main/java/com/official/memento/schedule/service/ScheduleCreateUseCase.java
  src/main/java/com/official/memento/schedule/service/ScheduleService.java
  src/main/java/com/official/memento/schedule/service/command/RepeatScheduleCreateCommand.java
  src/main/java/com/official/memento/schedule/service/command/ScheduleCreateCommand.java
  src/main/java/com/official/memento/tag/controller/TagApiController.java
  src/main/java/com/official/memento/tag/infrastructure/TagRepositoryAdapter.java
  src/main/java/com/official/memento/tag/infrastructure/persistence/TagEntityJpaRepository.java
  src/main/java/com/official/memento/todo/domain/ToDo.java
  src/main/java/com/official/memento/todo/infrastructure/persistence/ToDoEntity.java
Labels: enhancement

#38 스케줄 삭제 구현
  src/main/java/com/official/memento/schedule/conntroller/ScheduleApiController.java
  src/main/java/com/official/memento/schedule/domain/ScheduleRepository.java
  src/main/java/com/official/memento/schedule/infrastructure/ScheduleRepositoryAdapter.java
  src/main/java/com/official/memento/schedule/infrastructure/persistence/ScheduleEntity.java
  src/main/java/com/official/memento/schedule/infrastructure/persistence/ScheduleEntityJpaRepository.java
  src/main/java/com/official/memento/schedule/service/ScheduleDeleteAllUseCase.java
  src/main/java/com/official/memento/schedule/service/ScheduleDeleteUseCase.java
  src/main/java/com/official/memento/schedule/service/ScheduleService.java
  src/main/java/com/official/memento/schedule/service/command/ScheduleDeleteAllCommand.java
  src/main/java/com/official/memento/schedule/service/command/ScheduleDeleteCommand.java
Labels: enhancement

#49 fix: Swagger 설정 수정
  gradle/libs.versions.toml
  src/main/java/com/official/memento/global/config/SwaggerConfig.java
Labels: setting

#50 Refactor: MemberPersonalInfo update api
  src/main/java/com/official/memento/global/config/SwaggerConfig.java
  src/main/java/com/official/memento/member/controller/MemberApiController.java
  src/main/java/com/official/memento/member/controller/MemberPersonalInfoApiController.java
  src/main/java/com/official/memento/member/controller/MemberPersonalInfoApiDocs.java
  src/main/java/com/official/memento/member/controller/dto/MemberPersonalInfoRequest.java
  src/main/java/com/official/memento/member/controller/dto/MemberPersonalInfoResponse.java
  src/main/java/com/official/memento/member/domain/port/MemberPersonalInfoRepository.java
  src/main/java/com/official/memento/member/infrastructure/MemberPersonalInfoRepositoryAdapter.java
  src/main/java/com/official/memento/member/infrastructure/persistence/MemberPersonalInfoEntity.java
  src/main/java/com/official/memento/member/infrastructure/persistence/MemberPersonalInfoEntityJpaRepository.java
  src/main/java/com/official/memento/member/service/MemberPersonalInfoService.java
  src/main/java/com/official/memento/member/service/MemberService.java
  src/main/java/com/official/memento/member/service/usecase/MemberPersonalInfoUpdateUseCase.java
Labels: refactor

#51 단일 ToDo 삭제 API 구현
  src/main/java/com/official/memento/todo/controller/ToDoApiController.java
  src/main/java/com/official/memento/todo/domain/ToDoRepository.java
  src/main/java/com/official/memento/todo/infrastructure/ToDoRepositoryAdapter.java
  src/main/java/com/official/memento/todo/infrastructure/persistence/ToDoEntity.java
  src/main/java/com/official/memento/todo/service/ToDoCreateUseCase.java
  src/main/java/com/official/memento/todo/service/ToDoDeleteUseCase.java
  src/main/java/com/official/memento/todo/service/ToDoService.java
  src/main/java/com/official/memento/todo/service/command/ToDoDeleteCommand.java
Labels: enhancement

#45 Feat/#23 schedule
  src/main/java/com/official/memento/schedule/conntroller/ScheduleApiController.java
  src/main/java/com/official/memento/schedule/conntroller/dto/request/ScheduleUpdateGroupRequest.java
  src/main/java/com/official/memento/schedule/conntroller/dto/request/ScheduleUpdateRequest.java
  src/main/java/com/official/memento/schedule/domain/Schedule.java
  src/main/java/com/official/memento/schedule/domain/ScheduleRepository.java
  src/main/java/com/official/memento/schedule/domain/ScheduleTag.java
  src/main/java/com/official/memento/schedule/domain/ScheduleTagRepository.java
  src/main/java/com/official/memento/schedule/infrastructure/ScheduleRepositoryAdapter.java
  src/main/java/com/official/memento/schedule/infrastructure/ScheduleTagRepositoryAdapter.java
  src/main/java/com/official/memento/schedule/infrastructure/persistence/ScheduleEntity.java
  src/main/java/com/official/memento/schedule/infrastructure/persistence/ScheduleEntityJpaRepository.java
  src/main/java/com/official/memento/schedule/infrastructure/persistence/ScheduleTagEntity.java
  src/main/java/com/official/memento/schedule/infrastructure/persistence/ScheduleTagEntityJpaRepository.java
  src/main/java/com/official/memento/schedule/service/ScheduleDeleteAllUseCase.java
  src/main/java/com/official/memento/schedule/service/ScheduleDeleteGroupUseCase.java
  src/main/java/com/official/memento/schedule/service/ScheduleDeleteUseCase.java
  src/main/java/com/official/memento/schedule/service/ScheduleService.java
  src/main/java/com/official/memento/schedule/service/ScheduleUpdateGroupUseCase.java
  src/main/java/com/official/memento/schedule/service/ScheduleUpdateUseCase.java
  src/main/java/com/official/memento/schedule/service/command/ScheduleDeleteAllCommand.java
  src/main/java/com/official/memento/schedule/service/command/ScheduleDeleteGroupCommand.java
  src/main/java/com/official/memento/schedule/service/command/ScheduleUpdateCommand.java
  src/main/java/com/official/memento/schedule/service/command/ScheduleUpdateGroupCommand.java
Labels: enhancement

#56 Feat/#46 orders
  src/main/java/com/official/memento/orderinfo/controller/OrderInfoApiController.java
  src/main/java/com/official/memento/orderinfo/domain/OrderInfo.java
  src/main/java/com/official/memento/orderinfo/domain/OrderInfoRepository.java
  src/main/java/com/official/memento/orderinfo/domain/OrderWithScheduleOrToDo.java
  src/main/java/com/official/memento/orderinfo/domain/PlanType.java
  src/main/java/com/official/memento/orderinfo/infrastructure/OrderInfoRepositoryAdapter.java
  src/main/java/com/official/memento/orderinfo/infrastructure/persistence/OrderInfoEntity.java
  src/main/java/com/official/memento/orderinfo/infrastructure/persistence/OrderInfoEntityJpaRepository.java
  src/main/java/com/official/memento/orderinfo/infrastructure/persistence/projection/OrderInfoProjection.java
  src/main/java/com/official/memento/orderinfo/service/OrderInfoService.java
  src/main/java/com/official/memento/schedule/conntroller/ScheduleApiController.java
  src/main/java/com/official/memento/schedule/domain/ScheduleRepository.java
  src/main/java/com/official/memento/schedule/domain/ScheduleTagRepository.java
  src/main/java/com/official/memento/schedule/domain/entity/Schedule.java
  src/main/java/com/official/memento/schedule/domain/entity/ScheduleTag.java
  src/main/java/com/official/memento/schedule/infrastructure/ScheduleRepositoryAdapter.java
  src/main/java/com/official/memento/schedule/infrastructure/ScheduleTagRepositoryAdapter.java
  src/main/java/com/official/memento/schedule/infrastructure/persistence/ScheduleEntity.java
  src/main/java/com/official/memento/schedule/infrastructure/persistence/ScheduleEntityJpaRepository.java
  src/main/java/com/official/memento/schedule/infrastructure/persistence/ScheduleTagEntity.java
  src/main/java/com/official/memento/schedule/infrastructure/persistence/ScheduleTagEntityJpaRepository.java
  src/main/java/com/official/memento/schedule/service/ScheduleAllGetUseCase.java
  src/main/java/com/official/memento/schedule/service/ScheduleService.java
  src/main/java/com/official/memento/schedule/service/usecase/RepeatScheduleCreateUseCase.java
  src/main/java/com/official/memento/schedule/service/usecase/ScheduleCreateUseCase.java
  src/main/java/com/official/memento/schedule/service/usecase/ScheduleDeleteGroupUseCase.java
  src/main/java/com/official/memento/schedule/service/usecase/ScheduleDeleteUseCase.java
  src/main/java/com/official/memento/schedule/service/usecase/ScheduleUpdateGroupUseCase.java
  src/main/java/com/official/memento/schedule/service/usecase/ScheduleUpdateUseCase.java
  src/main/java/com/official/memento/todo/infrastructure/persistence/ToDoTagEntity.java
  src/main/java/com/official/memento/todo/service/ToDoService.java
Labels: enhancement

#63 ToDo 완료 상태 변경 API 구현
  src/main/java/com/official/memento/global/annotation/AuthorizationUser.java
  src/main/java/com/official/memento/todo/controller/ToDoApiController.java
  src/main/java/com/official/memento/todo/controller/dto/ToDoGetResponse.java
  src/main/java/com/official/memento/todo/domain/ToDo.java
  src/main/java/com/official/memento/todo/infrastructure/ToDoRepositoryAdapter.java
  src/main/java/com/official/memento/todo/infrastructure/ToDoTagRepositoryAdapter.java
  src/main/java/com/official/memento/todo/infrastructure/persistence/ToDoEntity.java
  src/main/java/com/official/memento/todo/service/ToDoGetUseCase.java
  src/main/java/com/official/memento/todo/service/ToDoService.java
  src/main/java/com/official/memento/todo/service/ToDoUpdateUseCase.java
  src/main/java/com/official/memento/todo/service/command/ToDoCompletionUpdateCommand.java
Labels: enhancement

#66 refactor: api swagger 문서 업데이트
  src/main/java/com/official/memento/schedule/conntroller/ScheduleApiController.java
  src/main/java/com/official/memento/schedule/conntroller/ScheduleApiControllerDocs.java
  src/main/java/com/official/memento/schedule/conntroller/ScheduleApiDocs.java
  src/main/java/com/official/memento/schedule/conntroller/dto/request/RepeatScheduleCreateRequest.java
  src/main/java/com/official/memento/schedule/conntroller/dto/request/ScheduleCreateRequest.java
  src/main/java/com/official/memento/schedule/conntroller/dto/request/ScheduleUpdateGroupRequest.java
  src/main/java/com/official/memento/schedule/conntroller/dto/request/ScheduleUpdateRequest.java
Labels: documentation, refactor

#67 Feat/#61 get schedules
  src/main/java/com/official/memento/schedule/conntroller/ScheduleApiController.java
  src/main/java/com/official/memento/schedule/conntroller/dto/response/AllDaySchedulesResponse.java
  src/main/java/com/official/memento/schedule/conntroller/dto/response/ScheduleAllAllDaysGetResponse.java
  src/main/java/com/official/memento/schedule/conntroller/dto/response/ScheduleAllGetResponse.java
  src/main/java/com/official/memento/schedule/conntroller/dto/response/ScheduleCreateResponse.java
  src/main/java/com/official/memento/schedule/conntroller/dto/response/ScheduleDetailResponse.java
  src/main/java/com/official/memento/schedule/conntroller/dto/response/ScheduleWithOrderInfo.java
  src/main/java/com/official/memento/schedule/domain/ScheduleRepository.java
  src/main/java/com/official/memento/schedule/domain/entity/Schedule.java
  src/main/java/com/official/memento/schedule/infrastructure/ScheduleRepositoryAdapter.java
  src/main/java/com/official/memento/schedule/infrastructure/persistence/ScheduleEntityJpaRepository.java
  src/main/java/com/official/memento/schedule/infrastructure/persistence/projection/ScheduleOrderInfoProjection.java
  src/main/java/com/official/memento/schedule/service/ScheduleAllGetUseCase.java
  src/main/java/com/official/memento/schedule/service/ScheduleService.java
  src/main/java/com/official/memento/schedule/service/usecase/ScheduleGetUseCase.java
Labels: enhancement

#68 fix: authorization memberId null로 받아지는 문제 해결
  src/main/java/com/official/memento/auth/service/AuthService.java
  src/main/java/com/official/memento/auth/service/JwtUtil.java
  src/main/java/com/official/memento/global/config/AuthorizationConfig.java
  src/main/java/com/official/memento/global/resolver/AuthArgumentResolver.java
  src/main/java/com/official/memento/member/controller/MemberPersonalInfoApiController.java
  src/main/resources/application-local.yml
Labels: bugfix

#72 fix: API 수정
  src/main/java/com/official/memento/auth/controller/AuthApiController.java
  src/main/java/com/official/memento/auth/controller/dto/AuthApiRequest.java
  src/main/java/com/official/memento/auth/controller/dto/AuthApiResponse.java
  src/main/java/com/official/memento/auth/service/AuthResult.java
  src/main/java/com/official/memento/auth/service/AuthService.java
  src/main/java/com/official/memento/auth/service/JwtUtil.java
  src/main/java/com/official/memento/auth/service/command/AuthCommand.java
  src/main/java/com/official/memento/global/config/ObjectMapperConfig.java
  src/main/java/com/official/memento/global/exception/ErrorCode.java
  src/main/java/com/official/memento/global/exception/InvalidRequestBodyException.java
  src/main/java/com/official/memento/global/handler/GlobalExceptionHandler.java
  src/main/java/com/official/memento/member/controller/dto/MemberPersonalInfoRequest.java
  src/main/java/com/official/memento/member/controller/dto/MemberPersonalInfoResponse.java
  src/main/java/com/official/memento/member/domain/Member.java
  src/main/java/com/official/memento/member/infrastructure/persistence/MemberPersonalInfoMapper.java
  src/main/java/com/official/memento/member/service/usecase/MemberPersonalInfoRetrieveUseCase.java
  src/main/java/com/official/memento/member/service/usecase/MemberPersonalInfoUpdateUseCase.java
  src/main/java/com/official/memento/schedule/conntroller/dto/request/ScheduleCreateRequest.java
Labels: bugfix

#75 fix: 순서 기능
  src/main/java/com/official/memento/orderinfo/infrastructure/OrderInfoRepositoryAdapter.java
  src/main/java/com/official/memento/orderinfo/infrastructure/persistence/OrderInfoEntityJpaRepository.java
  src/main/java/com/official/memento/orderinfo/infrastructure/persistence/projection/OrderInfoProjection.java
Labels: bugfix

#76 feat: 투두 리스트 반환 API 구현
  src/main/java/com/official/memento/orderinfo/domain/OrderInfoRepository.java
  src/main/java/com/official/memento/orderinfo/infrastructure/OrderInfoRepositoryAdapter.java
  src/main/java/com/official/memento/orderinfo/infrastructure/persistence/OrderInfoEntityJpaRepository.java
  src/main/java/com/official/memento/schedule/domain/ScheduleTagRepository.java
  src/main/java/com/official/memento/todo/controller/ToDoApiController.java
  src/main/java/com/official/memento/todo/controller/dto/ToDoAllGetResponse.java
  src/main/java/com/official/memento/todo/controller/dto/ToDoCompletionResponse.java
  src/main/java/com/official/memento/todo/controller/dto/ToDoCreateRequest.java
  src/main/java/com/official/memento/todo/controller/dto/ToDoGetResponse.java
  src/main/java/com/official/memento/todo/controller/dto/ToDoUpdateRequest.java
  src/main/java/com/official/memento/todo/domain/ToDo.java
  src/main/java/com/official/memento/todo/domain/ToDoRepository.java
  src/main/java/com/official/memento/todo/infrastructure/ToDoRepositoryAdapter.java
  src/main/java/com/official/memento/todo/infrastructure/persistence/ToDoEntity.java
  src/main/java/com/official/memento/todo/infrastructure/persistence/ToDoJpaRepository.java
  src/main/java/com/official/memento/todo/infrastructure/persistence/ToDoTagEntity.java
  src/main/java/com/official/memento/todo/infrastructure/persistence/ToDoTagJpaRepository.java
  src/main/java/com/official/memento/todo/service/ToDoGetUseCase.java
  src/main/java/com/official/memento/todo/service/ToDoService.java
  src/main/java/com/official/memento/todo/service/ToDoUpdateUseCase.java
  src/main/java/com/official/memento/todo/service/command/ToDoCreateCommand.java
  src/main/java/com/official/memento/todo/service/command/ToDoUpdateCommand.java
Labels: enhancement, bugfix

#81 Feat/#79 link
  src/main/java/com/official/memento/schedule/conntroller/ScheduleApiController.java
  src/main/java/com/official/memento/schedule/conntroller/dto/request/SchedulesCreateRequest.java
  src/main/java/com/official/memento/schedule/service/ScheduleService.java
  src/main/java/com/official/memento/schedule/service/command/SchedulesCreateCommand.java
  src/main/java/com/official/memento/schedule/service/usecase/ScheduleCreateUseCase.java
  src/main/java/com/official/memento/tag/domain/TagRepository.java
  src/main/java/com/official/memento/tag/infrastructure/TagRepositoryAdapter.java
  src/main/java/com/official/memento/tag/infrastructure/persistence/TagJpaRepository.java
Labels: enhancement

#80 feat: 투두 드래그앤드랍 API
  src/main/java/com/official/memento/orderinfo/domain/OrderInfo.java
  src/main/java/com/official/memento/orderinfo/domain/OrderInfoRepository.java
  src/main/java/com/official/memento/orderinfo/infrastructure/OrderInfoRepositoryAdapter.java
  src/main/java/com/official/memento/orderinfo/infrastructure/persistence/OrderInfoEntity.java
  src/main/java/com/official/memento/orderinfo/infrastructure/persistence/OrderInfoEntityJpaRepository.java
  src/main/java/com/official/memento/todo/controller/ToDoApiController.java
  src/main/java/com/official/memento/todo/controller/dto/ToDoDragAndDropRequest.java
  src/main/java/com/official/memento/todo/domain/ToDo.java
  src/main/java/com/official/memento/todo/infrastructure/ToDoRepositoryAdapter.java
  src/main/java/com/official/memento/todo/infrastructure/persistence/ToDoJpaRepository.java
  src/main/java/com/official/memento/todo/infrastructure/persistence/projection/ToDoWithOrderProjection.java
  src/main/java/com/official/memento/todo/service/ToDoService.java
  src/main/java/com/official/memento/todo/service/ToDoUpdateUseCase.java
  src/main/java/com/official/memento/todo/service/command/ToDoPositionUpdateCommand.java
Labels: enhancement

#87 fix: 투두 get API
  src/main/java/com/official/memento/todo/controller/dto/ToDoGetResponse.java
Labels: bugfix

#89 fix: null 분기 처리
  src/main/java/com/official/memento/todo/service/ToDoService.java
Labels: bugfix

#90 fix: order 값 null 예외 처리
  src/main/java/com/official/memento/todo/service/ToDoService.java
Labels: bugfix

#91 feat: 에러
  src/main/java/com/official/memento/auth/service/JwtUtil.java
  src/main/java/com/official/memento/global/exception/ErrorCode.java
  src/main/java/com/official/memento/global/exception/MementoException.java
  src/main/java/com/official/memento/global/handler/GlobalExceptionHandler.java
Labels: enhancement

#94 Feat/#93 get date todo
  src/main/java/com/official/memento/orderinfo/domain/OrderInfo.java
  src/main/java/com/official/memento/orderinfo/infrastructure/OrderInfoRepositoryAdapter.java
  src/main/java/com/official/memento/orderinfo/infrastructure/persistence/OrderInfoMapper.java
  src/main/java/com/official/memento/todo/controller/ToDoApiController.java
  src/main/java/com/official/memento/todo/controller/dto/ToDoGetResponse.java
  src/main/java/com/official/memento/todo/domain/ToDo.java
  src/main/java/com/official/memento/todo/service/ToDoGetUseCase.java
  src/main/java/com/official/memento/todo/service/ToDoService.java
Labels: enhancement

#98 feat: 투두 디테일 반환 API
  src/main/java/com/official/memento/todo/controller/ToDoApiController.java
  src/main/java/com/official/memento/todo/controller/dto/ToDoDetailGetResponse.java
  src/main/java/com/official/memento/todo/domain/ToDo.java
  src/main/java/com/official/memento/todo/domain/ToDoTag.java
  src/main/java/com/official/memento/todo/service/ToDoGetUseCase.java
  src/main/java/com/official/memento/todo/service/ToDoService.java
  src/main/kotlin/com/official/memento/todo/service/ToDoPrioritizationService.kt
Labels: enhancement

#100 fix: 클라 이슈 대응
  src/main/java/com/official/memento/schedule/conntroller/dto/response/ScheduleWithOrderInfo.java
  src/main/java/com/official/memento/tag/infrastructure/persistence/TagJpaRepository.java
Labels: bugfix

#103 fix: 스웨거 보강/관리
  src/main/java/com/official/memento/todo/controller/ToDoApiController.java
  src/main/java/com/official/memento/todo/controller/ToDoApiDocs.java
Labels: documentation
